GameClient: *
	javac -cp .:../lib/bridj-0.7-20140918.jar:../lib/dx-1.7.jar:../lib/logback-classic-1.0.13.jar:../lib/logback-core-1.0.13.jar:../lib/slf4j-api-1.7.2.jar:../lib/webcam-capture-0.3.12-20161206.184756-3.jar GameClient.java

run:
	java -cp .:../lib/bridj-0.7-20140918.jar:../lib/dx-1.7.jar:../lib/logback-classic-1.0.13.jar:../lib/logback-core-1.0.13.jar:../lib/slf4j-api-1.7.2.jar:../lib/webcam-capture-0.3.12-20161206.184756-3.jar GameClient


